### ISSUE TITLE
Support for Visionic MCT-340 E

### ISSUE THREAD

**Issue by sl33nyc** [rcloran/bellows#36]
Full disclosure: I'm a total newbie to home automation with Zigbee.  I've managed to control my GE Link light bulbs with a USB Zigbee stick and bellows.

I'm trying to use bellows with the door sensor, [Visionic MCT-340 E](https://www.amazon.com/Visonic-MCT-340-Wireless-Window-Sensor/dp/B06XDJ3KYC), but have found it difficult getting started.  I managed getting the door sensor to join my Zigbee network (`bellows form; bellows permit`), but I don't understand the work flow from that point.  Do I use bellows to poll the sensors for state of the door sensor, or is there a standard way to register a callback whenever the door sensor state changes?

I would love any sort of help or pointers just getting started!  A link to some relevant source code or script with some light commentary would be extremely helpful.

**Comment by rcloran** [comment]
The Zigbee Cluster Library (http://www.zigbee.org/non-menu-pages/zigbee-cluster-library-specification-download/) and the Zigbee Home Automation Public Application Profile (http://www.zigbee.org/zigbee-for-developers/applicationstandards/zigbeehomeautomation/) documents describe the relevant layers of the Zigbee specification, assuming this device is standards compliant. The Home Assistant code for the zha component of the binary sensor platform (https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/binary_sensor/zha.py) is an example use of bellows to interact with an IAS Zone device.
