### ISSUE TITLE
Support for ConBee and RaspBee hardware by Dresden Elektronik

### ISSUE THREAD

**Issue by Gamester17** [rcloran/bellows#50]
@rcloran would you please consider adding RaspBee ZigBee Shield for Raspberry Pi and ConBee USB dongle hardware, both made by Dresden Elektronik

ConBee (v1/v2) and RaspBee by Dresden Elektronik are the two of the most commonly/popularly sold as DIY ZigBee radio adapters available in Europe, and they are of course also available in North America too. With them being relativly inexpensive and supporting ZigBee PRO, ZigBee Home Automation (ZHA), and ZigBee Light Link (ZLL) 

https://www.dresden-elektronik.de/conbee/?L=1&ref=gh
https://www.amazon.com/NEW-gateway-compact-certified-operating/dp/B01FDWOIHK/

https://www.dresden-elektronik.de/raspbee/?L=1&ref=gh
https://www.amazon.com/RaspBee-premium-ZigBee-Raspberry-Firmware/dp/B00E6300DO/

https://www.dresden-elektronik.de/funktechnik/service/download/driver/?L=1

Official open source implementations by Dresden Elektronik themselves :

https://github.com/dresden-elektronik
https://github.com/dresden-elektronik/basic-aps-plugin
https://github.com/dresden-elektronik/deconz-rest-plugin
https://github.com/dresden-elektronik/deconz-rest-doc

Dresden Elektronik today their own ZigBee gateway software called "deCONZ" which has APIs for both ConBee and RaspBee hardware.

https://www.dresden-elektronik.de/funktechnik/products/software/pc/deconz/?L=1

The goal and wish would be to be able to use these relativly cheap ConBee and RaspBee hardware adapters in Home Assistant and Hass.io

**Comment by rcloran** [comment]
I'm planning on splitting out the zigbee parts of bellows (soon -- work is in progress), which will allow using that with libraries that interface with other . Adding support for new radios is not a goal for bellows at the moment.

**Comment by Gamester17** [comment]
@rcloran that is cool, however if you change your mind Dresden Elektronik have offered to donate RaspBee/ConBee hardware to developers Home Assistant if they would like to implement support for them, see @manup comment here:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

**Comment by abmantis** [comment]
Hey @rcloran, any progress on the split?

**Comment by Gamester17** [comment]
@rcloran FYI; here is a link to the serial UART protocol documentation used by ConBee and RaspBee hardware:

http://www.dresden-elektronik.de/rpi/deconz/deCONZ-Serial-Protocol-en.pdf

PS: If send a mail to support@dresden-elektronik.de and reference Manu they can send a RaspBee and a ConBee. 

This above information was provided my manup (Manuel Pietschmann) here => https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

**Comment by Gamester17** [comment]
@rcloran any news on splitting out the Zigbee parts of bellows?

That is, to allow using it with libraries that interface with other.

**Comment by Gamester17** [comment]
@rcloran any chance that you could reconsider adding deCONZ Serial Protocol support to bellows?

http://www.dresden-elektronik.de/rpi/deconz/deCONZ-Serial-Protocol-en.pdf

manup from Dresden-Elektronik said that they will send you a free ConBee and Raspbee if you post here:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/158

**Comment by Gamester17** [comment]
@AndreasBomholtz is this maybe something that you would be interested in?

**Comment by Equidamoid** [comment]
Hi everyone (@rcloran?). 
Is there any update or plans? I'm considering writing a python wrapper for their serial api and don't really want to reinvent the wheel if someone already works on it =)
